/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

declare module 'vue' {
  export interface GlobalComponents {
    DialogBox: (typeof import('./src/components/dialogBox/index.vue'))['default']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElDivider: (typeof import('element-plus/es'))['ElDivider']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElImage: (typeof import('element-plus/es'))['ElImage']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElProgress: (typeof import('element-plus/es'))['ElProgress']
    ElRadio: (typeof import('element-plus/es'))['ElRadio']
    ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    ElSwitch: (typeof import('element-plus/es'))['ElSwitch']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    Fluid: (typeof import('./src/components/fluid/index.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Tray: (typeof import('./src/components/tray/index.vue'))['default']
  }
}
